### ISSUE TITLE
Project Learning

### ISSUE THREAD

**Issue by yileicc** [RmdanJr/vehicle-distance-estimation#10]
Hello, I am a first-year doctoral student. My current research area is monocular ranging. I found your project on GitHub and I am very interested in it. Unfortunately, when studying your project, I could not find the scripts folder and the kitti-dataset folder and the related python files. Could you provide this part? Thank you very much for your help.

**Comment by RmdanJr** [comment]
Hello @yileicc,

Sorry for the late response.

Scripts directories and relevant Python files are nested under both [`object-detector`](https://github.com/RmdanJr/vehicle-distance-estimation/tree/main/object-detector) and [`distance-estimator`](https://github.com/RmdanJr/vehicle-distance-estimation/tree/main/distance-estimator) directories. Regarding the KITTI dataset, [this script ](https://github.com/RmdanJr/vehicle-distance-estimation/blob/main/distance-estimator/scripts/download-kitti-dataset.sh) downloads it.

Please follow the instructions mentioned in the README file in order. It has all the steps needed to get this project up.

Don't hesitate to reach out if you have any other questions.
