### ISSUE TITLE
ImportError: cannot import name 'multi_gpu_model' from 'tensorflow.python.keras.utils'

### ISSUE THREAD

**Issue by HassanBinHaroon** [RmdanJr/vehicle-distance-estimation#3]
I had to install tensorflow for it so I tried this way as well. But it did not work.
![Capture](https://user-images.githubusercontent.com/104098902/182401758-47dc6b73-7de2-4590-ae9d-1af28361b606.PNG)

**Comment by RmdanJr** [comment]
I think if you installed project dependencies from both `/object-detector/requirements.txt` and `/distance-estimator/requirements.txt`, #1, #2, and #3 will be solved.

**Comment by HassanBinHaroon** [comment]
@RmdanJr, @Ahmedabdelalem61, @WeaamMohamed, @EngAhmedElkady  Please Check out my following implementation of your work on Google Colab. You can refer the following on your repository if you like. Thanks! 

https://github.com/HassanBinHaroon/object_detection-PLUS-distance_estimation-v1

**Comment by HassanBinHaroon** [comment]
I realised that this issue has to do with the version of Keras that is used within Tensorflow. I encountered the same problem in Colab when using version 2.4.3.

so my work around was to uninstall Keras 2.4.3 like so:
!pip uninstall Keras

and then installing a slightly older version Keras 2.2.4:
!pip install keras==2.2.4

This solved the problem problem for me

NB: You might need to restart the runtime for this to take effect

**Comment by HassanBinHaroon** [comment]
> I had to install tensorflow for it so I tried this way as well. But it did not work. ![Capture](https://user-images.githubusercontent.com/104098902/182401758-47dc6b73-7de2-4590-ae9d-1af28361b606.PNG)

One solution is to simply comment off this line.
