### ISSUE TITLE
From where I can get train.csv and test.csv? How are they created? 

### ISSUE THREAD

**Issue by HassanBinHaroon** [RmdanJr/vehicle-distance-estimation#4]
Only annotations.csv is created when I run generate-csv.py. No, test/train.csv is created.
![Capture](https://user-images.githubusercontent.com/104098902/182402462-bbc9838f-1ab6-46b4-a304-43d3d2dd5467.PNG)

**Comment by RmdanJr** [comment]
You can generate both `train.csv` and `test.csv` files from KITTI dataset labels.
`generate-csv.py` is used to generate CSV files from any .txt labels, just pass the name of the generated file from CLI.

**Comment by HassanBinHaroon** [comment]
@RmdanJr There are just training labels present in KITTI datasets and no test labels. You recommend to split training labels into training and test labels?

**Comment by RmdanJr** [comment]
Yup

**Comment by HassanBinHaroon** [comment]
Okay Thanks!

**Comment by HassanBinHaroon** [comment]
@RmdanJr Is generate-csv.py **not** required while running **just inference**?

**Comment by HassanBinHaroon** [comment]
@RmdanJr Is generate-csv.py required only for training?

**Comment by HassanBinHaroon** [comment]
@RmdanJr I am running only inference now. Can you please click on the following link and **validate my method**. **Am I using the rights commands with correct sequence**? 

I am using my own video for the inference (saved on my google drive).

https://colab.research.google.com/drive/1RumXRaRNLUyAzdjJIpZF3WdCdX5gz8Md#scrollTo=1TQ8OSYSO0H5

**Comment by RmdanJr** [comment]
YES, generate-csv.py is required only for training.
In inference, we use a CSV file that contains object coordinates to estimate the distance.
This file is generated automatically as output after running the object detector.

**Comment by RmdanJr** [comment]
Your notebook is private, I need your access to view it.
Please read the readme file, tutorial notebooks, and docs, they contain all the details you may need to know about how the project works and how to use it.

**Comment by HassanBinHaroon** [comment]
> Your notebook is private, I need your access to view it. Please read the readme file, tutorial notebooks, and docs, they contain all the details you may need to know about how the project works and how to use it.

I am doing it public. Kindly take a look at it.

**Comment by HassanBinHaroon** [comment]
> Your notebook is private, I need your access to view it. Please read the readme file, tutorial notebooks, and docs, they contain all the details you may need to know about how the project works and how to use it.

its public now.

**Comment by HassanBinHaroon** [comment]
One solution is to simply comment off this line.
