### ISSUE TITLE
not able to import multi_gpu_model

### ISSUE THREAD

**Issue by Saikrishna129** [RmdanJr/vehicle-distance-estimation#5]
i dont knew where it was going wrong but ,i wasnt able to download multi_gpu_model
![image](https://user-images.githubusercontent.com/73346136/200864753-cde66d27-7a6a-481d-b91d-be454d6c7a68.png)

**Comment by Saikrishna129** [comment]
can u pls reply to this asap,pls help me out

**Comment by RmdanJr** [comment]
https://github.com/RmdanJr/vehicle-distance-estimation/issues/3#issuecomment-1217293400

**Comment by HassanBinHaroon** [comment]
I realised that this issue has to do with the version of Keras that is used within Tensorflow. I encountered the same problem in Colab when using version 2.4.3.

so my work around was to uninstall Keras 2.4.3 like so:
!pip uninstall Keras

and then installing a slightly older version Keras 2.2.4:
!pip install keras==2.2.4

This solved the problem problem for me

NB: You might need to restart the runtime for this to take effect

Worked for me.

**Comment by HassanBinHaroon** [comment]
> i dont knew where it was going wrong but ,i wasnt able to download multi_gpu_model ![image](https://user-images.githubusercontent.com/73346136/200864753-cde66d27-7a6a-481d-b91d-be454d6c7a68.png)

One solution is to simply comment off this line.
