### ISSUE TITLE
train.csv and test.csv

### ISSUE THREAD

**Issue by shermangugu** [RmdanJr/vehicle-distance-estimation#6]
Hello
I have a problem about distance estimation.
After i use ' python generate-csv.py --input=kitti-dataset/train_annots/ --filename=annotations.csv --results . ' i only got an  annotations.csv.
In the step of Train Model, where are train.csv and test.csv obtained from?

Thank!

**Comment by RmdanJr** [comment]
Hello @shermangugu 
Kindly check my comments on this issue.
https://github.com/RmdanJr/vehicle-distance-estimation/issues/4
